### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by iinastyiii** [clarityzzz/KeyboardX#1]
Bottom bar (emoji & microphone) doesn’t show fully and is cut off half way.

**Comment by iinastyiii** [comment]
Does work with colorboard. Apologize I had something else enabled that was preventing it.  Only issue I’ve found with it. Is the bottom bar images being cut off.

**Comment by clarityzzz** [comment]
@iinastyiii hey, what is your device?

**Comment by clarityzzz** [comment]
I'll be launching v0.0.2 briefly to fix this issue. Closing.

**Comment by iinastyiii** [comment]
Thanks for quick response on this sorry just seen the replies/emails. 

Only keyboard tweak I have is colorboard and iPhone X tweaks would be statusBarX.

**Comment by clarityzzz** [comment]
No problem mate, I'm on it ;)
