### ISSUE TITLE
Not perfect with barmoji

### ISSUE THREAD

**Issue by a7lafe** [clarityzzz/KeyboardX#3]
The emojis show half not all i mean they like cutting

**Comment by clarityzzz** [comment]
It's because of a tweak that's coloring your keyboard. Fixing this for Colorboard and keyboardcolorxll, if there's any other let me know.

**Comment by a7lafe** [comment]
Yes I disabled the tweak from icleaner its dark keybad and work perfectly
thank u and good job

**Comment by clarityzzz** [comment]
@a7lafe I've submitted v0.0.2 that hopefully solves all compatibility issues.

**Comment by a7lafe** [comment]
Ok will try enable the dark keybad when i get the update

**Comment by clarityzzz** [comment]
Considering fixed. Closing.
